#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');
const { loadAgent } = require('./parse-agent');
const {
  DEFAULT_CODEX_AGENT_CONFIG,
  resolveCodexAgentSettings,
} = require('./model-config');

function renderCodexToml(parsedAgent, options = {}) {
  const settings = resolveCodexAgentSettings(
    parsedAgent,
    options.agentConfig || DEFAULT_CODEX_AGENT_CONFIG,
  );
  const maxChars = options.maxChars === undefined ? 4000 : Number(options.maxChars);
  const description = (parsedAgent.frontmatter.description || '').replace(/"/g, '\\"');
  const instructions = maxChars > 0 && parsedAgent.body.length > maxChars
    ? parsedAgent.body.slice(0, maxChars) + '\n\n[Truncated by Citadel projection. See canonical agent definition for full instructions.]'
    : parsedAgent.body;

  return [
    '# Generated by Citadel. Do not edit manually.',
    `# Source: agents/${parsedAgent.frontmatter.name || parsedAgent.name}.md`,
    '',
    `name = "${parsedAgent.frontmatter.name || parsedAgent.name}"`,
    `description = "${description}"`,
    `model = "${settings.model}"`,
    `model_reasoning_effort = "${settings.reasoningEffort}"`,
    '',
    'developer_instructions = """',
    instructions,
    '"""',
    '',
  ].join('\n');
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function projectAgentToCodex(agentPath, targetBaseDir, options = {}) {
  const parsedAgent = loadAgent(agentPath);
  if (parsedAgent.errors && parsedAgent.errors.length > 0) {
    throw new Error(`Agent "${parsedAgent.name}" has validation errors: ${parsedAgent.errors.join(', ')}`);
  }
  const targetPath = path.join(targetBaseDir, `${parsedAgent.frontmatter.name || parsedAgent.name}.toml`);
  const toml = renderCodexToml(parsedAgent, options);

  if (!options.dryRun) {
    ensureDir(path.dirname(targetPath));
    fs.writeFileSync(targetPath, toml, 'utf8');
  }

  return {
    parsedAgent,
    output: {
      tomlPath: targetPath,
      toml,
    },
  };
}

module.exports = Object.freeze({
  renderCodexToml,
  projectAgentToCodex,
});
