#!/usr/bin/env node
'use strict';

const childProcess = require('child_process');
const fs = require('fs');
const path = require('path');
const config = require('../core/config');
const {
  collectSkillCandidates,
  normalizeRoutingInput,
  parseDeterministicCommand,
  parseRequestEnvelope,
  resolveDeterministicCommand,
  routeForSkill,
  validateRouteOverride,
} = require('../core/skills/routing');

function parseArgs(argv) {
  const args = {
    input: [],
    json: false,
    projectRoot: process.cwd(),
    routeOverride: null,
    help: false,
  };

  for (let index = 0; index < argv.length; index++) {
    const arg = argv[index];
    if (arg === '--json') args.json = true;
    else if (arg === '--project-root') args.projectRoot = path.resolve(argv[++index] || '.');
    else if (arg === '--route') {
      const value = argv[++index];
      if (!value) throw new Error('--route requires a route such as /test-gen');
      args.routeOverride = value;
    }
    else if (arg === '--help' || arg === '-h') args.help = true;
    else if (arg === '--') {
      args.input.push(...argv.slice(index + 1));
      break;
    }
    else args.input.push(arg);
  }

  return {
    ...args,
    input: args.input.join(' ').trim(),
  };
}

function usage() {
  return [
    'Usage:',
    '  node scripts/route-preview.js [--json] [--project-root <path>] [--route </skill>] -- <request>',
    '',
    'Shows the proportional /do route, alternatives, boundary, and verification before execution.',
  ].join('\n');
}

function loadSkills() {
  const tablePath = path.join(__dirname, '..', 'core', 'skills', 'routing-table.json');
  const table = JSON.parse(fs.readFileSync(tablePath, 'utf8'));
  return table.skills.map((entry) => ({
    name: entry.name,
    route: routeForSkill(entry.name),
    keywords: entry.keywords,
    productBundle: entry.productBundle,
  }));
}

// Generated by scripts/generate-routing.js from skills/*/SKILL.md frontmatter.
const SKILLS = loadSkills();

function words(value) {
  return String(value || '').trim().split(/\s+/).filter(Boolean);
}

function keywordMatches(input) {
  return collectSkillCandidates(input, SKILLS);
}

function explicitIntentRoute(input, matches) {
  const lower = normalizeRoutingInput(input);
  const routes = new Set(matches.map((item) => item.route));
  if (/^(code\s+)?review\b/.test(lower) && routes.has('/review')) {
    return {
      route: '/review',
      reason: 'explicit leading review intent wins over secondary file or documentation keywords.',
    };
  }
  if (/^(document|docs|write docs|update docs)\b/.test(lower) && routes.has('/doc-gen')) {
    return {
      route: '/doc-gen',
      reason: 'explicit leading documentation intent wins over secondary file keywords.',
    };
  }
  return null;
}

function hasSingleFileSignal(input) {
  return /\b[\w.-]+\.(js|jsx|ts|tsx|mjs|cjs|json|md|css|html|py|rb|go|rs|java|cs)\b/i.test(input);
}

function classifyComplexity(input, matches) {
  const count = words(input).length;
  const lower = normalizeRoutingInput(input);
  const parallel = /\b(parallel|simultaneous|multiple agents|at the same time|both\b.+\band)\b/i.test(input);
  const persistent = /\b(campaign|multi-session|phases|overnight|continue until|run until)\b/i.test(input);
  const crossDomain = /\b(platform|across|all|entire|multi-repo|cross-repo|multiple repos)\b/i.test(input);
  const taste = /\b(design|experience|quality|polish|intuitive)\b/i.test(input);
  const complexity = persistent || parallel || crossDomain ? 4 : count > 24 || taste ? 3 : matches.length > 1 ? 3 : count > 8 ? 2 : 1;

  return {
    scope: crossDomain ? 'cross-domain' : hasSingleFileSignal(input) ? 'single-file' : 'single-domain',
    complexity,
    requiresPersistence: persistent,
    requiresParallel: parallel,
    requiresTaste: taste,
  };
}

function selectTier0(input) {
  return parseDeterministicCommand(input);
}

function candidateList(matches) {
  return matches.map((item) => ({
    name: item.name,
    route: item.route,
    matches: item.matches,
    productBundle: item.productBundle,
  }));
}

function semanticDecision(fields) {
  return {
    ...fields,
    selected: null,
    command: null,
    final: false,
    requiresSemanticClassification: true,
    canRunNow: false,
    boundary: 'semantic-classification-required',
  };
}

function selectAutomaticRoute(input, mode = 'execute', options = {}) {
  if (!input.trim()) {
    return {
      mode,
      tier: 0,
      selected: '/do --list',
      command: '/do --list',
      reason: 'empty input should show available routes instead of guessing.',
      resolver: 'exact-command',
      final: true,
      requiresSemanticClassification: false,
      candidates: [],
      confidence: 'high',
      alternatives: [],
      verification: 'Confirm the skill list renders and asks for a direction.',
      dimensions: classifyComplexity(input, []),
    };
  }

  const tier0 = resolveDeterministicCommand(selectTier0(input), options.projectRoot);
  if (tier0) {
    if (!tier0.final) {
      return semanticDecision({
        mode,
        tier: 0,
        suggestedRoute: null,
        reason: tier0.reason,
        resolver: 'exact-command-capability-missing',
        candidates: [],
        confidence: 'high',
        alternatives: alternativesFor(input, []),
        verification: tier0.verification,
        dimensions: classifyComplexity(input, []),
        capability: tier0.capability,
      });
    }

    return {
      mode,
      tier: 0,
      selected: tier0.selected,
      command: tier0.command,
      reason: tier0.reason,
      resolver: 'exact-command',
      final: true,
      requiresSemanticClassification: false,
      candidates: [],
      confidence: 'high',
      alternatives: alternativesFor(input, []),
      verification: tier0.verification,
      dimensions: classifyComplexity(input, []),
      capability: tier0.capability,
    };
  }

  const matches = keywordMatches(input);
  const dimensions = classifyComplexity(input, matches);
  if (matches.length === 1) {
    const selected = matches[0].route;
    const reason = `one keyword group produced ${matches[0].route} as a candidate: ${matches[0].matches.join(', ')}.`;

    return semanticDecision({
      mode,
      tier: 2,
      suggestedRoute: selected,
      reason: `${reason} This is candidate evidence; semantic classification must confirm the route.`,
      resolver: 'semantic-candidate',
      candidates: candidateList(matches),
      confidence: 'candidate',
      alternatives: alternativesFor(input, matches),
      verification: verificationFor(selected),
      dimensions,
    });
  }

  if (matches.length > 1) {
    const explicit = explicitIntentRoute(input, matches);
    if (explicit) {
      return semanticDecision({
        mode,
        tier: 2,
        suggestedRoute: explicit.route,
        reason: `${explicit.reason} This is candidate evidence; semantic classification must confirm the route.`,
        resolver: 'semantic-candidate',
        candidates: candidateList(matches),
        confidence: 'candidate',
        alternatives: alternativesFor(input, matches),
        verification: verificationFor(explicit.route),
        dimensions,
      });
    }

    return semanticDecision({
      mode,
      tier: 3,
      suggestedRoute: '/marshal',
      reason: `multiple route families matched (${matches.slice(0, 3).map((item) => item.route).join(', ')}), so Marshal should sequence the work before escalating.`,
      resolver: 'semantic-candidate',
      candidates: candidateList(matches),
      confidence: 'candidate',
      alternatives: alternativesFor(input, matches),
      verification: verificationFor('/marshal'),
      dimensions,
    });
  }

  let selected = fallbackRoute(dimensions);
  let reason = fallbackReason(selected, dimensions);
  const proportional = applyProportionality(input, selected, dimensions);
  selected = proportional.selected;
  if (proportional.reason) reason = proportional.reason;

  return semanticDecision({
    mode,
    tier: 3,
    suggestedRoute: selected,
    reason: `${reason} This is a non-final proportional suggestion; semantic classification must confirm the route.`,
    resolver: 'semantic-required',
    candidates: [],
    confidence: 'candidate',
    alternatives: alternativesFor(input, matches),
    verification: verificationFor(selected),
    dimensions,
  });
}

function selectRoute(input, options = {}) {
  const envelope = parseRequestEnvelope(input, { mode: options.mode });
  const automatic = selectAutomaticRoute(envelope.request, envelope.mode, {
    projectRoot: options.projectRoot,
  });
  const routeOverride = validateRouteOverride(options.routeOverride, SKILLS);
  if (!routeOverride) {
    return {
      ...automatic,
      originalInput: envelope.originalInput,
      request: envelope.request,
    };
  }

  return {
    ...automatic,
    originalInput: envelope.originalInput,
    request: envelope.request,
    selected: routeOverride,
    command: routeOverride,
    suggestedRoute: automatic.suggestedRoute || null,
    automaticSelection: automatic.selected || automatic.suggestedRoute || null,
    resolver: 'override',
    final: true,
    requiresSemanticClassification: false,
    canRunNow: false,
    boundary: 'activation-preflight-required',
    confidence: 'explicit',
    reason: `explicit validated route override selected ${routeOverride}; activation and execution boundaries still apply.`,
    verification: verificationFor(routeOverride),
  };
}

function fallbackRoute(dimensions) {
  if (dimensions.requiresParallel) return '/fleet --quick';
  if (dimensions.requiresPersistence || dimensions.complexity >= 4) return '/archon';
  if (dimensions.complexity <= 1) return 'direct-edit';
  return '/marshal';
}

function fallbackReason(selected, dimensions) {
  if (selected === '/fleet --quick') return 'the request signals independent parallel work.';
  if (selected === '/archon') return 'the request appears persistent or campaign-sized.';
  if (selected === 'direct-edit') return 'the request appears small enough for a direct edit.';
  return 'the request needs sequencing but not campaign persistence yet.';
}

function applyProportionality(input, selected, dimensions) {
  if (selected.startsWith('/fleet') && dimensions.scope === 'single-file') {
    return {
      selected: '/marshal',
      reason: 'proportionality downgraded Fleet because the request mentions a single file.',
    };
  }
  if ((selected === '/archon' || selected.startsWith('/fleet')) && words(input).length < 20) {
    return {
      selected: '/marshal',
      reason: 'proportionality downgraded campaign-level routing because the input is brief.',
    };
  }
  return { selected, reason: null };
}

function alternativesFor(_input, matches) {
  const alternatives = [];
  for (const item of matches.slice(0, 4)) {
    alternatives.push({
      route: item.route,
      why: `matched ${item.matches.join(', ')}`,
    });
  }

  if (!alternatives.some((item) => item.route === '/marshal')) {
    alternatives.push({ route: '/marshal', why: 'safe fallback for unclear multi-step work' });
  }
  if (!alternatives.some((item) => item.route === '/archon')) {
    alternatives.push({ route: '/archon', why: 'use only when persistence or phases are needed' });
  }
  if (!alternatives.some((item) => item.route === '/fleet --quick')) {
    alternatives.push({ route: '/fleet --quick', why: 'use only for independent parallel scopes' });
  }
  return alternatives.slice(0, 5);
}

function verificationFor(route) {
  if (route === '/loop') return 'Confirm the loop contract has an explicit verifier, attempt limit, stop status, and .planning/loops state path.';
  if (route === '/marshal') return 'Confirm the selected skill sequence, changed files, and final verification command.';
  if (route === '/archon') return 'Confirm campaign phases, claimed scope, exit evidence, and verification profile.';
  if (route.startsWith('/fleet')) return 'Confirm independent scopes, merge order, and per-branch verification reports.';
  if (route === 'direct-edit') return 'Inspect the diff and run the smallest relevant verification command.';
  if (route.startsWith('/')) return `Confirm ${route} reports its own handoff and verification evidence.`;
  return 'Run the command and confirm it exits 0 or reports actionable failures.';
}

function gitDirty(projectRoot) {
  const result = childProcess.spawnSync('git', ['status', '--short'], {
    cwd: projectRoot,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'],
  });
  if (result.status !== 0) return false;
  return Boolean(String(result.stdout || '').trim());
}

function boundaryFor(route, dirty) {
  if (dirty && route !== '/dashboard' && route !== '/do operator') {
    return {
      canRunNow: false,
      boundary: 'worktree-review',
      risk: 'low',
      approval: 'Review uncommitted worktree changes before starting the routed action.',
    };
  }
  if (route === '/fleet --quick') {
    return {
      canRunNow: false,
      boundary: 'parallel-agent-approval',
      risk: 'medium-high',
      approval: 'Approve Fleet only after scopes are independent and merge order is clear.',
    };
  }
  if (route === '/archon') {
    return {
      canRunNow: false,
      boundary: 'campaign-approval',
      risk: 'medium',
      approval: 'Approve campaign persistence after phases and exit evidence are clear.',
    };
  }
  return {
    canRunNow: true,
    boundary: route.startsWith('/') ? 'agent-route' : 'local-command',
    risk: route === 'direct-edit' ? 'low' : 'medium',
    approval: null,
  };
}

function skillNameForRoute(route) {
  const match = String(route || '').trim().match(/^\/([a-z][a-z0-9-]*)/i);
  return match ? match[1].toLowerCase() : null;
}

function activationBoundary(projectRoot, selected, options = {}) {
  const skill = skillNameForRoute(selected);
  if (!skill) return { skill: null, context: null, decision: null };
  const context = options.activationContext || config.loadActivationContext(projectRoot, {
    runtime: options.runtime,
    runtimeId: options.runtimeId,
    env: options.env,
  });
  return {
    skill,
    context: {
      status: context.status,
      persisted: context.persisted !== false,
      reasonCode: context.reasonCode,
      receiptPath: context.receiptPath,
    },
    decision: config.preflightRoute(context, skill),
  };
}

function buildPreview(input, options = {}) {
  const projectRoot = path.resolve(options.projectRoot || process.cwd());
  const selected = selectRoute(input, {
    mode: 'preview',
    routeOverride: options.routeOverride,
    projectRoot,
  });
  const dirty = options.gitDirty === undefined ? gitDirty(projectRoot) : Boolean(options.gitDirty);
  let boundary = {
    canRunNow: false,
    boundary: 'semantic-classification-required',
    risk: 'low',
    approval: 'Run the full /do protocol to inspect active state, discover project skills, and semantically classify before execution.',
  };
  let activation = { skill: null, context: null, decision: null };

  if (selected.final) {
    boundary = boundaryFor(selected.selected, dirty);
    activation = activationBoundary(projectRoot, selected.selected, options);
    if (activation.decision
      && !['enabled', 'degraded'].includes(activation.decision.status)) {
      boundary = {
        canRunNow: false,
        boundary: 'product-bundle-activation',
        risk: 'low',
        approval: activation.decision.plan?.applyCommand
          ? `Review the activation plan, then explicitly apply: ${activation.decision.plan.applyCommand}`
          : `Resolve ${activation.decision.reasonCode} before invoking ${selected.selected}.`,
      };
    }
  }

  return {
    generatedAt: options.now || new Date().toISOString(),
    projectRoot,
    input: String(input || ''),
    ...selected,
    ...boundary,
    activation,
    gitDirty: dirty,
  };
}

function render(preview) {
  const routeLabel = preview.final ? 'Selected' : 'Suggested route';
  const routeValue = preview.final
    ? preview.selected
    : preview.suggestedRoute || '(runtime semantic classification required)';
  const commandValue = preview.final ? preview.command : '(none; preview is non-executable)';
  const lines = [
    'Routing Preview',
    '='.repeat(40),
    `Input: ${preview.input || '(empty)'}`,
    `${routeLabel}: ${routeValue}`,
    `Command: ${commandValue}`,
    `Tier: ${preview.tier}`,
    `Resolver: ${preview.resolver}`,
    `Confidence: ${preview.confidence}`,
    `Why: ${preview.reason}`,
    '',
    'Dimensions',
    `  Scope: ${preview.dimensions.scope}`,
    `  Complexity: ${preview.dimensions.complexity}`,
    `  Persistence: ${preview.dimensions.requiresPersistence ? 'yes' : 'no'}`,
    `  Parallel: ${preview.dimensions.requiresParallel ? 'yes' : 'no'}`,
    `  Taste: ${preview.dimensions.requiresTaste ? 'yes' : 'no'}`,
    '',
    'Boundary',
    `  Can run now: ${preview.canRunNow ? 'yes' : 'no'}`,
    `  Boundary: ${preview.boundary}`,
    `  Risk: ${preview.risk}`,
  ];

  if (preview.approval) lines.push(`  Approval: ${preview.approval}`);
  if (preview.activation?.decision) {
    lines.push(`  Product bundle: ${preview.activation.decision.bundleId}`);
    lines.push(`  Activation: ${preview.activation.decision.status} (${preview.activation.decision.reasonCode})`);
    lines.push(`  Effective config: ${preview.activation.context.status}${preview.activation.context.persisted ? '' : ' (bootstrap preview; not persisted)'}`);
  }

  lines.push('');
  lines.push('Candidates');
  if (preview.candidates.length === 0) lines.push('  - none from deterministic keyword evidence');
  for (const candidate of preview.candidates) {
    lines.push(`  - ${candidate.route}: matched ${candidate.matches.join(', ')}`);
  }

  lines.push('');
  lines.push('Alternatives');
  for (const alternative of preview.alternatives) {
    lines.push(`  - ${alternative.route}: ${alternative.why}`);
  }

  lines.push('');
  lines.push('Verify');
  lines.push(`  ${preview.verification}`);
  return `${lines.join('\n')}\n`;
}

function main() {
  try {
    const args = parseArgs(process.argv.slice(2));
    if (args.help) {
      process.stdout.write(`${usage()}\n`);
      return;
    }

    const preview = buildPreview(args.input, {
      projectRoot: args.projectRoot,
      routeOverride: args.routeOverride,
    });
    if (args.json) process.stdout.write(`${JSON.stringify(preview, null, 2)}\n`);
    else process.stdout.write(render(preview));
  } catch (error) {
    process.stderr.write(`[route-preview] ${error.message}\n`);
    process.exitCode = 2;
  }
}

if (require.main === module) main();

module.exports = {
  buildPreview,
  keywordMatches,
  parseArgs,
  render,
  selectRoute,
  skillNameForRoute,
  usage,
};
